# fly.toml app configuration file generated for anagram-solver on 2023-08-17T22:29:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anagram-solver"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
